
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FECHACHAVE = 5;
  public static final int ABRECOLCHETE = 6;
  public static final int DOISPONTOS = 8;
  public static final int ABRECHAVE = 4;
  public static final int EOF = 0;
  public static final int STRING = 2;
  public static final int VIRGULA = 9;
  public static final int FECHACOLCHETE = 7;
  public static final int NUMERO = 3;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "NUMERO",
  "ABRECHAVE",
  "FECHACHAVE",
  "ABRECOLCHETE",
  "FECHACOLCHETE",
  "DOISPONTOS",
  "VIRGULA"
  };
}

